window.phaseRules = {
  LEAGUE: { label: "Primeira fase" },
  PLAYOFF: { label: "Playoff 1ª fase" },
  ROUND_OF_16: { label: "Oitavas" },
  QUARTER: { label: "Quartas de final" },
  SEMI: { label: "Semifinal" },
  FINAL: { label: "Final" },
};

window.superclassicConfig = {
  eligiblePhases: ["LEAGUE", "PLAYOFF", "ROUND_OF_16", "QUARTER"],
  eligibleTeams: [
    "Real Madrid",
    "Barcelona",
    "Bayern de Munique",
    "Manchester City",
    "Liverpool",
    "Chelsea",
    "Paris Saint-Germain",
  ],
};

window.participants = [
  ["leo-picca", "Leo Picca", "UCL-101"],
  ["leo-raposo", "Leo Raposo", "UCL-102"],
  ["serginho", "Serginho", "UCL-103"],
  ["biel", "Biel", "UCL-104"],
  ["rafinha", "Rafinha", "UCL-105"],
  ["ranieri", "Ranieri", "UCL-106"],
  ["nanel", "Nanel", "UCL-107"],
  ["marcel", "Marcel", "UCL-108"],
  ["dan", "Dan", "UCL-109"],
  ["celsinho", "Celsinho", "UCL-110"],
  ["enrico", "Enrico", "UCL-111"],
  ["gui-giron", "Gui Giron", "UCL-112"],
  ["scarpa", "Scarpa", "UCL-113"],
  ["victor", "Victor", "UCL-114"],
  ["faber", "Faber", "UCL-115"],
  ["felippe-leite", "Felippe Leite", "UCL-116"],
  ["muca", "Muca", "UCL-117"],
  ["feijao", "Feijão", "UCL-118"],
  ["ivan", "Ivan", "UCL-119"],
  ["michel", "Michel", "UCL-120"],
  ["deco", "Deco", "UCL-121"],
].map(([id, name, accessCode], index) => ({
  id,
  name,
  accessCode,
  color: ["#4ecdc4", "#ffd166", "#ff6b6b", "#7b9cff"][index % 4],
}));

window.competitionAssets = {
  mark: "./assets/champions-league-mark.png",
  trophy: "./assets/champions-league-trophy.jpeg",
};

window.competitionSnapshot = {
  leaguePhaseMatches: 144,
  playoffMatches: 16,
  roundOf16Matches: 16,
  quarterFinalists: 8,
};

window.quarterFinalsFormsConfig = {
  csvUrl: "",
  submitUrl: "",
  fieldMap: {
    participant: "",
    Q1_ida_home: "",
    Q1_ida_away: "",
    Q1_volta_home: "",
    Q1_volta_away: "",
    Q1_classificado: "",
    Q2_ida_home: "",
    Q2_ida_away: "",
    Q2_volta_home: "",
    Q2_volta_away: "",
    Q2_classificado: "",
    Q3_ida_home: "",
    Q3_ida_away: "",
    Q3_volta_home: "",
    Q3_volta_away: "",
    Q3_classificado: "",
    Q4_ida_home: "",
    Q4_ida_away: "",
    Q4_volta_home: "",
    Q4_volta_away: "",
    Q4_classificado: "",
  },
  description:
    "Cole a URL CSV publicada do Forms para leitura do ranking e, opcionalmente, configure submitUrl + fieldMap para envio automático.",
  expectedColumns: [
    "Timestamp",
    "Participante",
    "Q1_ida_home",
    "Q1_ida_away",
    "Q1_volta_home",
    "Q1_volta_away",
    "Q1_classificado",
    "Q2_ida_home",
    "Q2_ida_away",
    "Q2_volta_home",
    "Q2_volta_away",
    "Q2_classificado",
    "Q3_ida_home",
    "Q3_ida_away",
    "Q3_volta_home",
    "Q3_volta_away",
    "Q3_classificado",
    "Q4_ida_home",
    "Q4_ida_away",
    "Q4_volta_home",
    "Q4_volta_away",
    "Q4_classificado",
  ],
};

window.leagueSuperclassicFormsConfig = {
  formUrl: "",
  description:
    "Espaço para palpites de placar dos superclássicos da 1ª fase. Você pode preencher aqui e copiar o texto para enviar no fluxo oficial.",
};

window.teamLogos = {
  Ajax: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.ajax.nl",
  "Real Madrid": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.realmadrid.com",
  Liverpool: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.liverpoolfc.com",
  Barcelona: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.fcbarcelona.com",
  "Paris Saint-Germain": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.psg.fr",
  "Bayern München": "https://www.google.com/s2/favicons?sz=128&domain_url=https://fcbayern.com",
  "Bayern de Munique": "https://www.google.com/s2/favicons?sz=128&domain_url=https://fcbayern.com",
  "Manchester City": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.mancity.com",
  Arsenal: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.arsenal.com",
  Internazionale: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.inter.it",
  Inter: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.inter.it",
  Juventus: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.juventus.com",
  "Borussia Dortmund": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.bvb.de",
  Chelsea: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.chelseafc.com",
  Benfica: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.slbenfica.pt",
  Napoli: "https://www.google.com/s2/favicons?sz=128&domain_url=https://sscnapoli.it",
  "Atlético de Madrid": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.atleticodemadrid.com",
  "Bayer Leverkusen": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.bayer04.de",
  Leverkusen: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.bayer04.de",
  Tottenham: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.tottenhamhotspur.com",
  "Sporting CP": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.sporting.pt",
  Sporting: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.sporting.pt",
  Atalanta: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.atalanta.it",
  Marseille: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.om.fr",
  Monaco: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.asmonaco.com",
  "Kairat Almaty": "https://www.google.com/s2/favicons?sz=128&domain_url=https://fckairat.com",
  Pafos: "https://www.google.com/s2/favicons?sz=128&domain_url=https://pafosfc.com.cy",
  "Athletic Club": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.athletic-club.eus",
  Newcastle: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.newcastleunited.com",
  "Newcastle United": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.newcastleunited.com",
  Copenhagen: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.fck.dk",
  "PSV Eindhoven": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.psv.nl",
  Qarabağ: "https://www.google.com/s2/favicons?sz=128&domain_url=https://qarabagh.com",
  Frankfurt: "https://www.google.com/s2/favicons?sz=128&domain_url=https://en.eintracht.de",
  "Slavia Praha": "https://www.google.com/s2/favicons?sz=128&domain_url=https://en.slavia.cz",
  "Union Saint-Gilloise": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.rusg.brussels",
  Villarreal: "https://www.google.com/s2/favicons?sz=128&domain_url=https://villarrealcf.es",
  "Bodø/Glimt": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.glimt.no",
  Galatasaray: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.galatasaray.org",
  "Club Brugge": "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.clubbrugge.be",
  Olympiacos: "https://www.google.com/s2/favicons?sz=128&domain_url=https://www.olympiacos.org",
};

window.knockoutResults = [
  {
    id: "PO1",
    phase: "PLAYOFF",
    roundLabel: "Playoff - ida",
    kickoff: "2026-02-17T17:00:00-03:00",
    homeTeam: "Galatasaray",
    awayTeam: "Juventus",
    scoreFinal: { home: 5, away: 2 },
    aggregate: "5-2",
  },
  {
    id: "PO2",
    phase: "PLAYOFF",
    roundLabel: "Playoff - ida",
    kickoff: "2026-02-17T17:00:00-03:00",
    homeTeam: "Monaco",
    awayTeam: "Paris Saint-Germain",
    scoreFinal: { home: 2, away: 3 },
    aggregate: "2-3",
  },
  {
    id: "PO3",
    phase: "PLAYOFF",
    roundLabel: "Playoff - ida",
    kickoff: "2026-02-17T17:00:00-03:00",
    homeTeam: "Borussia Dortmund",
    awayTeam: "Atalanta",
    scoreFinal: { home: 2, away: 0 },
    aggregate: "2-0",
  },
  {
    id: "PO4",
    phase: "PLAYOFF",
    roundLabel: "Playoff - ida",
    kickoff: "2026-02-17T17:00:00-03:00",
    homeTeam: "Benfica",
    awayTeam: "Real Madrid",
    scoreFinal: { home: 0, away: 1 },
    aggregate: "0-1",
  },
  {
    id: "PO5",
    phase: "PLAYOFF",
    roundLabel: "Playoff - ida",
    kickoff: "2026-02-18T17:00:00-03:00",
    homeTeam: "Qarabağ",
    awayTeam: "Newcastle",
    scoreFinal: { home: 1, away: 6 },
    aggregate: "1-6",
  },
  {
    id: "PO6",
    phase: "PLAYOFF",
    roundLabel: "Playoff - ida",
    kickoff: "2026-02-18T17:00:00-03:00",
    homeTeam: "Club Brugge",
    awayTeam: "Atlético de Madrid",
    scoreFinal: { home: 3, away: 3 },
    aggregate: "3-3",
  },
  {
    id: "PO7",
    phase: "PLAYOFF",
    roundLabel: "Playoff - ida",
    kickoff: "2026-02-18T17:00:00-03:00",
    homeTeam: "Bodø/Glimt",
    awayTeam: "Inter",
    scoreFinal: { home: 3, away: 1 },
    aggregate: "3-1",
  },
  {
    id: "PO8",
    phase: "PLAYOFF",
    roundLabel: "Playoff - ida",
    kickoff: "2026-02-18T17:00:00-03:00",
    homeTeam: "Olympiacos",
    awayTeam: "Leverkusen",
    scoreFinal: { home: 0, away: 2 },
    aggregate: "0-2",
  },
  {
    id: "PO9",
    phase: "PLAYOFF",
    roundLabel: "Playoff - volta",
    kickoff: "2026-02-24T17:00:00-03:00",
    homeTeam: "Atlético de Madrid",
    awayTeam: "Club Brugge",
    scoreFinal: { home: 4, away: 1 },
    aggregate: "7-4",
    qualified: "Atlético de Madrid",
  },
  {
    id: "PO10",
    phase: "PLAYOFF",
    roundLabel: "Playoff - volta",
    kickoff: "2026-02-24T17:00:00-03:00",
    homeTeam: "Leverkusen",
    awayTeam: "Olympiacos",
    scoreFinal: { home: 0, away: 0 },
    aggregate: "2-0",
    qualified: "Leverkusen",
  },
  {
    id: "PO11",
    phase: "PLAYOFF",
    roundLabel: "Playoff - volta",
    kickoff: "2026-02-24T17:00:00-03:00",
    homeTeam: "Inter",
    awayTeam: "Bodø/Glimt",
    scoreFinal: { home: 1, away: 2 },
    aggregate: "2-5",
    qualified: "Bodø/Glimt",
  },
  {
    id: "PO12",
    phase: "PLAYOFF",
    roundLabel: "Playoff - volta",
    kickoff: "2026-02-24T17:00:00-03:00",
    homeTeam: "Newcastle",
    awayTeam: "Qarabağ",
    scoreFinal: { home: 3, away: 2 },
    aggregate: "9-3",
    qualified: "Newcastle",
  },
  {
    id: "PO13",
    phase: "PLAYOFF",
    roundLabel: "Playoff - volta",
    kickoff: "2026-02-25T17:00:00-03:00",
    homeTeam: "Atalanta",
    awayTeam: "Borussia Dortmund",
    scoreFinal: { home: 4, away: 1 },
    aggregate: "4-3",
    qualified: "Atalanta",
  },
  {
    id: "PO14",
    phase: "PLAYOFF",
    roundLabel: "Playoff - volta",
    kickoff: "2026-02-25T17:00:00-03:00",
    homeTeam: "Juventus",
    awayTeam: "Galatasaray",
    scoreFinal: { home: 3, away: 2 },
    aggregate: "5-7",
    extraTime: true,
    qualified: "Galatasaray",
  },
  {
    id: "PO15",
    phase: "PLAYOFF",
    roundLabel: "Playoff - volta",
    kickoff: "2026-02-25T17:00:00-03:00",
    homeTeam: "Paris Saint-Germain",
    awayTeam: "Monaco",
    scoreFinal: { home: 2, away: 2 },
    aggregate: "5-4",
    qualified: "Paris Saint-Germain",
  },
  {
    id: "PO16",
    phase: "PLAYOFF",
    roundLabel: "Playoff - volta",
    kickoff: "2026-02-25T17:00:00-03:00",
    homeTeam: "Real Madrid",
    awayTeam: "Benfica",
    scoreFinal: { home: 2, away: 1 },
    aggregate: "3-1",
    qualified: "Real Madrid",
  },
  {
    id: "R161",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - ida",
    kickoff: "2026-03-10T17:00:00-03:00",
    homeTeam: "Galatasaray",
    awayTeam: "Liverpool",
    scoreFinal: { home: 1, away: 0 },
    aggregate: "1-0",
  },
  {
    id: "R162",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - ida",
    kickoff: "2026-03-10T17:00:00-03:00",
    homeTeam: "Atalanta",
    awayTeam: "Bayern München",
    scoreFinal: { home: 1, away: 6 },
    aggregate: "1-6",
  },
  {
    id: "R163",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - ida",
    kickoff: "2026-03-10T17:00:00-03:00",
    homeTeam: "Atlético de Madrid",
    awayTeam: "Tottenham",
    scoreFinal: { home: 5, away: 2 },
    aggregate: "5-2",
  },
  {
    id: "R164",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - ida",
    kickoff: "2026-03-10T17:00:00-03:00",
    homeTeam: "Newcastle",
    awayTeam: "Barcelona",
    scoreFinal: { home: 1, away: 1 },
    aggregate: "1-1",
  },
  {
    id: "R165",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - ida",
    kickoff: "2026-03-11T17:00:00-03:00",
    homeTeam: "Leverkusen",
    awayTeam: "Arsenal",
    scoreFinal: { home: 1, away: 1 },
    aggregate: "1-1",
  },
  {
    id: "R166",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - ida",
    kickoff: "2026-03-11T17:00:00-03:00",
    homeTeam: "Bodø/Glimt",
    awayTeam: "Sporting CP",
    scoreFinal: { home: 3, away: 0 },
    aggregate: "3-0",
  },
  {
    id: "R167",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - ida",
    kickoff: "2026-03-11T17:00:00-03:00",
    homeTeam: "Paris Saint-Germain",
    awayTeam: "Chelsea",
    scoreFinal: { home: 5, away: 2 },
    aggregate: "5-2",
  },
  {
    id: "R168",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - ida",
    kickoff: "2026-03-11T17:00:00-03:00",
    homeTeam: "Real Madrid",
    awayTeam: "Manchester City",
    scoreFinal: { home: 3, away: 0 },
    aggregate: "3-0",
  },
  {
    id: "R169",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - volta",
    kickoff: "2026-03-17T17:00:00-03:00",
    homeTeam: "Sporting CP",
    awayTeam: "Bodø/Glimt",
    scoreFinal: { home: 5, away: 0 },
    aggregate: "5-3",
    extraTime: true,
    qualified: "Sporting CP",
  },
  {
    id: "R1610",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - volta",
    kickoff: "2026-03-17T17:00:00-03:00",
    homeTeam: "Arsenal",
    awayTeam: "Leverkusen",
    scoreFinal: { home: 2, away: 0 },
    aggregate: "3-1",
    qualified: "Arsenal",
  },
  {
    id: "R1611",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - volta",
    kickoff: "2026-03-17T17:00:00-03:00",
    homeTeam: "Chelsea",
    awayTeam: "Paris Saint-Germain",
    scoreFinal: { home: 0, away: 3 },
    aggregate: "2-8",
    qualified: "Paris Saint-Germain",
  },
  {
    id: "R1612",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - volta",
    kickoff: "2026-03-17T17:00:00-03:00",
    homeTeam: "Manchester City",
    awayTeam: "Real Madrid",
    scoreFinal: { home: 1, away: 2 },
    aggregate: "1-5",
    qualified: "Real Madrid",
  },
  {
    id: "R1613",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - volta",
    kickoff: "2026-03-18T17:00:00-03:00",
    homeTeam: "Barcelona",
    awayTeam: "Newcastle",
    scoreFinal: { home: 7, away: 2 },
    aggregate: "8-3",
    qualified: "Barcelona",
  },
  {
    id: "R1614",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - volta",
    kickoff: "2026-03-18T17:00:00-03:00",
    homeTeam: "Bayern München",
    awayTeam: "Atalanta",
    scoreFinal: { home: 4, away: 1 },
    aggregate: "10-2",
    qualified: "Bayern München",
  },
  {
    id: "R1615",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - volta",
    kickoff: "2026-03-18T17:00:00-03:00",
    homeTeam: "Liverpool",
    awayTeam: "Galatasaray",
    scoreFinal: { home: 4, away: 0 },
    aggregate: "4-1",
    qualified: "Liverpool",
  },
  {
    id: "R1616",
    phase: "ROUND_OF_16",
    roundLabel: "Oitavas - volta",
    kickoff: "2026-03-18T17:00:00-03:00",
    homeTeam: "Tottenham",
    awayTeam: "Atlético de Madrid",
    scoreFinal: { home: 3, away: 2 },
    aggregate: "5-7",
    qualified: "Atlético de Madrid",
  },
  {
    id: "QF1",
    phase: "QUARTER",
    roundLabel: "Quartas - ida",
    kickoff: "2026-04-07T16:00:00-03:00",
    homeTeam: "Sporting CP",
    awayTeam: "Arsenal",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "QF2",
    phase: "QUARTER",
    roundLabel: "Quartas - ida",
    kickoff: "2026-04-07T16:00:00-03:00",
    homeTeam: "Real Madrid",
    awayTeam: "Bayern München",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "QF3",
    phase: "QUARTER",
    roundLabel: "Quartas - ida",
    kickoff: "2026-04-08T16:00:00-03:00",
    homeTeam: "Barcelona",
    awayTeam: "Atlético de Madrid",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "QF4",
    phase: "QUARTER",
    roundLabel: "Quartas - ida",
    kickoff: "2026-04-08T16:00:00-03:00",
    homeTeam: "Paris Saint-Germain",
    awayTeam: "Liverpool",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "QF5",
    phase: "QUARTER",
    roundLabel: "Quartas - volta",
    kickoff: "2026-04-14T16:00:00-03:00",
    homeTeam: "Atlético de Madrid",
    awayTeam: "Barcelona",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "QF6",
    phase: "QUARTER",
    roundLabel: "Quartas - volta",
    kickoff: "2026-04-14T16:00:00-03:00",
    homeTeam: "Liverpool",
    awayTeam: "Paris Saint-Germain",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "QF7",
    phase: "QUARTER",
    roundLabel: "Quartas - volta",
    kickoff: "2026-04-15T16:00:00-03:00",
    homeTeam: "Arsenal",
    awayTeam: "Sporting CP",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "QF8",
    phase: "QUARTER",
    roundLabel: "Quartas - volta",
    kickoff: "2026-04-15T16:00:00-03:00",
    homeTeam: "Bayern München",
    awayTeam: "Real Madrid",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "SF1",
    phase: "SEMI",
    roundLabel: "Semifinal - ida",
    kickoff: "2026-04-28T16:00:00-03:00",
    homeTeam: "Paris/Liverpool",
    awayTeam: "Real Madrid/Bayern",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "SF2",
    phase: "SEMI",
    roundLabel: "Semifinal - ida",
    kickoff: "2026-04-29T16:00:00-03:00",
    homeTeam: "Barcelona/Atlético",
    awayTeam: "Sporting/Arsenal",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "SF3",
    phase: "SEMI",
    roundLabel: "Semifinal - volta",
    kickoff: "2026-05-05T16:00:00-03:00",
    homeTeam: "Sporting/Arsenal",
    awayTeam: "Barcelona/Atlético",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "SF4",
    phase: "SEMI",
    roundLabel: "Semifinal - volta",
    kickoff: "2026-05-06T16:00:00-03:00",
    homeTeam: "Real Madrid/Bayern",
    awayTeam: "Paris/Liverpool",
    scoreFinal: { home: null, away: null },
  },
  {
    id: "F1",
    phase: "FINAL",
    roundLabel: "Final",
    kickoff: "2026-05-30T13:00:00-03:00",
    homeTeam: "Vencedor SF1",
    awayTeam: "Vencedor SF2",
    scoreFinal: { home: null, away: null },
  },
];

const hopeSoloByParticipant = {
  Enrico: 1,
  Nanel: 1,
  Scarpa: 2,
  "Feijão": 1,
  Michel: 1,
};

window.leaguePhaseSnapshot = {
  phaseLabel: "Ranking oficial atualizado até o fim das oitavas",
  updatedAtLabel: "Base oficial validada pela planilha do bolão e resultados da UEFA.",
  leaderboard: [
    { position: 1, name: "Felippe Leite", total: 183.7, firstPhase: 106.9, playoff: 14, roundOf16: 56, superclassic: 6.8, favoriteTeam: "Real Madrid", assistPick: "Vitinha", scorerPick: "Erling Haaland" },
    { position: 2, name: "Serginho", total: 175.8, firstPhase: 102.6, playoff: 20.5, roundOf16: 51, superclassic: 1.7, favoriteTeam: "Barcelona", assistPick: "Lamine Yamal", scorerPick: "João Pedro" },
    { position: 3, name: "Biel", total: 167.15, firstPhase: 93.55, playoff: 10.5, roundOf16: 58, superclassic: 5.1, favoriteTeam: "Liverpool", assistPick: "Raphinha", scorerPick: "Ekitike" },
    { position: 4, name: "Michel", total: 163.25, firstPhase: 91.85, playoff: 16, roundOf16: 52, superclassic: 3.4, favoriteTeam: "Liverpool", assistPick: "Vinícius Jr.", scorerPick: "Harry Kane" },
    { position: 5, name: "Gui Giron", total: 161.1, firstPhase: 103.7, playoff: 11, roundOf16: 43, superclassic: 3.4, favoriteTeam: "Barcelona", assistPick: "Cole Palmer", scorerPick: "Robert Lewandowski" },
    { position: 6, name: "Rafinha", total: 159.4, firstPhase: 95, playoff: 13, roundOf16: 48, superclassic: 3.4, favoriteTeam: "Barcelona", assistPick: "Lamine Yamal", scorerPick: "Raphinha" },
    { position: 7, name: "Enrico", total: 157.55, firstPhase: 90.15, playoff: 13, roundOf16: 51, superclassic: 3.4, favoriteTeam: "Liverpool", assistPick: "Ousmane Dembélé", scorerPick: "Erling Haaland" },
    { position: 8, name: "Ranieri", total: 156.1, firstPhase: 91, playoff: 12, roundOf16: 48, superclassic: 5.1, favoriteTeam: "Barcelona", assistPick: "Lamine Yamal", scorerPick: "Robert Lewandowski" },
    { position: 9, name: "Faber", total: 154.45, firstPhase: 96.65, playoff: 11, roundOf16: 40, superclassic: 6.8, favoriteTeam: "Barcelona", assistPick: "Raphinha", scorerPick: "Kylian Mbappé" },
    { position: 10, name: "Victor", total: 153.85, firstPhase: 100.65, playoff: 10.5, roundOf16: 41, superclassic: 1.7, favoriteTeam: "Barcelona", assistPick: "Lamine Yamal", scorerPick: "Robert Lewandowski" },
    { position: 11, name: "Dan", total: 152.25, firstPhase: 91.85, playoff: 16, roundOf16: 41, superclassic: 3.4, favoriteTeam: "Liverpool", assistPick: "Lamine Yamal", scorerPick: "Raphinha" },
    { position: 12, name: "Scarpa", total: 151.3, firstPhase: 91.8, playoff: 12, roundOf16: 39, superclassic: 8.5, favoriteTeam: "Barcelona", assistPick: "Eberechi Eze", scorerPick: "Robert Lewandowski" },
    { position: 13, name: "Deco", total: 150.15, firstPhase: 86.75, playoff: 15, roundOf16: 45, superclassic: 3.4, favoriteTeam: "Barcelona", assistPick: "Vinícius Jr.", scorerPick: "Kylian Mbappé" },
    { position: 14, name: "Marcel", total: 149.7, firstPhase: 93, playoff: 12, roundOf16: 43, superclassic: 1.7, favoriteTeam: "Paris Saint-Germain", assistPick: "Désiré Doué", scorerPick: "Erling Haaland" },
    { position: 15, name: "Leo Raposo", total: 148.2, firstPhase: 95, playoff: 11.5, roundOf16: 40, superclassic: 1.7, favoriteTeam: "Barcelona", assistPick: "Mohamed Salah", scorerPick: "Mohamed Salah" },
    { position: 16, name: "Feijão", total: 148.1, firstPhase: 88.5, playoff: 15.5, roundOf16: 39, superclassic: 5.1, favoriteTeam: "Paris Saint-Germain", assistPick: "Raphinha", scorerPick: "Ousmane Dembélé" },
    { position: 17, name: "Leo Picca", total: 146.7, firstPhase: 83.1, playoff: 12.5, roundOf16: 46, superclassic: 5.1, favoriteTeam: "Real Madrid", assistPick: "Phil Foden", scorerPick: "Kylian Mbappé" },
    { position: 18, name: "Muca", total: 144.4, firstPhase: 91.6, playoff: 12, roundOf16: 34, superclassic: 6.8, favoriteTeam: "Barcelona", assistPick: "Mohamed Salah", scorerPick: "Erling Haaland" },
    { position: 19, name: "Ivan", total: 139.4, firstPhase: 81.7, playoff: 17, roundOf16: 39, superclassic: 1.7, favoriteTeam: "Barcelona", assistPick: "Lamine Yamal", scorerPick: "Raphinha" },
    { position: 20, name: "Celsinho", total: 135.75, firstPhase: 90.15, playoff: 12.5, roundOf16: 28, superclassic: 5.1, favoriteTeam: "Barcelona", assistPick: "Cole Palmer", scorerPick: "Raphinha" },
    { position: 21, name: "Nanel", total: 133.8, firstPhase: 92.5, playoff: 13.5, roundOf16: 21, superclassic: 6.8, favoriteTeam: "Chelsea", assistPick: "Lamine Yamal", scorerPick: "Harry Kane" },
  ].map((row) => ({
    ...row,
    hopeSolo: hopeSoloByParticipant[row.name] || 0,
  })),
};

window.participantSnapshots = Object.fromEntries(
  leaguePhaseSnapshot.leaderboard.map((row) => [
    participants.find((participant) => participant.name === row.name)?.id || row.name,
    row,
  ])
);

window.rulesHighlights = [
  "O ranking agora está atualizado até o fim das oitavas, com `Felippe Leite` líder em 183,7 pontos.",
  "A primeira fase da Champions no novo formato teve 144 partidas na fase de liga.",
  "Os resultados de playoff e oitavas vieram do site oficial da UEFA, atualizado em 18 de março de 2026.",
  "A soma total agora destaca separadamente 1ª fase, playoff 1ª fase e oitavas.",
  "Superclássicos seguem em coluna própria e são reconhecidos automaticamente até as quartas, com base na lista oficial de times elegíveis.",
  "A próxima etapa natural é ligar quartas, semi e final assim que os resultados forem acontecendo.",
];

window.rulesSections = [
  {
    title: "Pontuação por fase",
    items: [
      "Primeira fase: 0,85 ponto por acerto de resultado.",
      "Playoff 1ª fase: 0,50 ponto por acerto de resultado.",
      "Oitavas: 1,00 ponto por acerto de resultado.",
      "Quartas: 1,44 ponto por acerto de resultado.",
      "Semi: 2,08 pontos por acerto de resultado.",
      "Final: 7,00 pontos por acerto de resultado.",
    ],
  },
  {
    title: "Pontuação por classificação",
    items: [
      "Primeira fase: 4,2 pontos por classificado.",
      "Playoffs 1ª fase: 1,5 ponto por classificado.",
      "Oitavas: 3 pontos por classificado.",
      "Quartas: 4,32 pontos por classificado.",
      "Semi: 6,24 pontos por classificado.",
      "Final: 7,00 pontos por classificado.",
      "Na primeira fase, cada classificado na posição correta rende mais 2 pontos.",
    ],
  },
  {
    title: "Pontuação por placar exato",
    items: [
      "Primeira fase: não se aplica.",
      "Playoff 1ª fase: 3 pontos.",
      "Oitavas: 6 pontos.",
      "Quartas: 8,64 pontos.",
      "Semi: 12,48 pontos.",
      "Final: 23,80 pontos.",
    ],
  },
  {
    title: "Picks extras",
    items: [
      "Time favorito: 2 pontos na 1ª fase, 4 nas oitavas, 6 nas quartas, 8 na semi e 10 na final.",
      "O total máximo do time favorito é 30 pontos, se ele for campeão.",
      "Artilheiro: 15 pontos.",
      "Garçom: 15 pontos.",
      "Taça Guanabara: prêmio especial para o melhor pontuador da fase de grupos.",
    ],
  },
  {
    title: "Regras especiais",
    items: [
      "Superclássicos: o dobro da pontuação do placar exato em confrontos entre times elegíveis ao superclássico.",
      "A regra de superclássico vai somente até as quartas de final. Nas semifinais e na final ela não se aplica.",
      "Na 1ª fase, os placares dos superclássicos devem ser preenchidos no espaço dedicado da aba Superclássicos (separado da tendência da fase de liga).",
      "Hope Solo: quando apenas um participante é o único a acertar o jogo, seja no placar exato ou na tendência, a pontuação desse acerto é dobrada.",
      "Prorrogação: acertando o placar nos 90 minutos, vale a regra normal. Acertando apenas o placar da prorrogação, vale metade da pontuação normal de placar.",
      "Final empatada: se o apostador acertar o placar da final mas errar o campeão, recebe só os 23,80 pontos do placar, sem os pontos de classificação.",
    ],
  },
  {
    title: "Times elegíveis a superclássico",
    items: [
      "Real Madrid",
      "Barcelona",
      "Bayern de Munique",
      "Manchester City",
      "Liverpool",
      "Chelsea",
      "Paris Saint-Germain",
      "Qualquer confronto entre esses times entra automaticamente como superclássico na base de cálculo (somente em 1ª fase, playoff, oitavas e quartas).",
    ],
  },
];

window.predictionHighlightsByMatchTitle = {
  "Atlético de Madrid x Tottenham": {
    exact: [],
    tendency: [
      "Dan",
      "Felippe Leite",
      "Leo Raposo",
      "Gui Giron",
      "Scarpa",
      "Rafinha",
      "Biel",
      "Serginho",
      "Muca",
      "Leo Picca",
      "Enrico",
      "Faber",
      "Ranieri",
      "Feijão",
      "Michel",
      "Deco",
    ],
    sourceImage:
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.46.jpeg",
  },
  "Tottenham x Atlético de Madrid": {
    exact: [],
    tendency: ["Marcel", "Dan", "Victor", "Celsinho", "Feijão", "Michel"],
    sourceImage:
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.46.jpeg",
  },
  "Newcastle x Barcelona": {
    exact: ["Biel", "Enrico", "Ivan"],
    tendency: ["Scarpa", "Biel", "Enrico", "Ivan", "Leo Picca"],
    sourceImage:
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (2).jpeg",
  },
  "Barcelona x Newcastle": {
    exact: [],
    tendency: [
      "Marcel",
      "Dan",
      "Felippe Leite",
      "Leo Raposo",
      "Gui Giron",
      "Scarpa",
      "Rafinha",
      "Biel",
      "Serginho",
      "Muca",
      "Leo Picca",
      "Victor",
      "Enrico",
      "Nanel",
      "Faber",
      "Celsinho",
      "Ranieri",
      "Ivan",
      "Michel",
      "Deco",
    ],
    sourceImage:
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (2).jpeg",
  },
  "Paris Saint-Germain x Chelsea": {
    exact: [],
    tendency: [
      "Marcel",
      "Dan",
      "Felippe Leite",
      "Gui Giron",
      "Rafinha",
      "Muca",
      "Leo Picca",
      "Enrico",
      "Faber",
      "Feijão",
      "Deco",
    ],
    sourceImage:
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47.jpeg",
  },
  "Chelsea x Paris Saint-Germain": {
    exact: [],
    tendency: [
      "Felippe Leite",
      "Leo Raposo",
      "Rafinha",
      "Serginho",
      "Victor",
      "Nanel",
      "Faber",
      "Celsinho",
      "Feijão",
      "Ivan",
      "Deco",
    ],
    sourceImage:
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47.jpeg",
  },
  "Real Madrid x Manchester City": {
    exact: [],
    tendency: ["Marcel", "Leo Raposo", "Biel", "Leo Picca", "Enrico", "Michel", "Deco"],
    sourceImage:
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (1).jpeg",
  },
  "Manchester City x Real Madrid": {
    exact: [],
    tendency: ["Felippe Leite", "Leo Raposo", "Victor", "Ranieri"],
    sourceImage:
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (1).jpeg",
  },
};

window.officialSources = {
  rankingImage: "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Image 2026-03-18 at 19.33.01.jpeg",
  uefaResultsUrl:
    "https://www.uefa.com/uefachampionsleague/news/029c-1e9a2f63fe2d-ebf9ad643892-1000--2025-26-champions-league-all-the-fixtures-and-results/",
};

window.winnersHistory = [
  { season: "08/09", guanabara: "", first: "Felippe Leite", second: "Muca", third: "Brunão", fourth: "", participants: 3 },
  { season: "09/10", guanabara: "", first: "Felippe Leite", second: "Faber", third: "?", fourth: "?", participants: 6 },
  { season: "10/11", guanabara: "", first: "Rafinha", second: "Felippe Leite", third: "Claudio", fourth: "Muca", participants: 11 },
  { season: "11/12", guanabara: "", first: "Marcel", second: "Cláudio", third: "Rafinha", fourth: "Leo Picca", participants: 13 },
  { season: "12/13", guanabara: "", first: "Leo Picca", second: "Muca", third: "Marcel", fourth: "Serginho", participants: 12 },
  { season: "13/14", guanabara: "", first: "Leo Picca", second: "Leo Raposo", third: "Muca", fourth: "Beda", participants: 15 },
  { season: "14/15", guanabara: "", first: "Biel", second: "Brunão", third: "Leo Raposo", fourth: "Serginho", participants: 12 },
  { season: "15/16", guanabara: "", first: "Leo Raposo", second: "Leo Picca", third: "Marcel", fourth: "Scarpa", participants: 14 },
  { season: "16/17", guanabara: "", first: "Leo Raposo", second: "Leo Picca", third: "Enrico", fourth: "Biel", participants: 16 },
  { season: "17/18", guanabara: "Scarpa", first: "Leo Raposo", second: "Niel", third: "Biel", fourth: "Victor", participants: 19 },
  { season: "18/19", guanabara: "Leo Raposo", first: "Marcel", second: "Dan", third: "Felippe Leite", fourth: "Leo Raposo", participants: 16 },
  { season: "19/20", guanabara: "Rafinha", first: "Faber", second: "Dan", third: "Nanel", fourth: "Marcel", participants: 17 },
  { season: "20/21", guanabara: "Marcel / Biel", first: "Leo Picca", second: "Leo Raposo", third: "Serginho", fourth: "Biel", participants: 17 },
  { season: "21/22", guanabara: "Leo Raposo", first: "Leo Raposo", second: "Gui Giron", third: "Rafinha", fourth: "Felippe Leite", participants: 18 },
  { season: "22/23", guanabara: "Leo Raposo", first: "Ranieri", second: "Leo Raposo", third: "Gui Giron", fourth: "Biel", participants: 20 },
  { season: "23/24", guanabara: "Felippe Leite", first: "Dan", second: "Serginho", third: "Michel", fourth: "Leo Raposo", participants: 20 },
  { season: "24/25", guanabara: "Leo Raposo", first: "Muca", second: "Leo Raposo", third: "Feijão", fourth: "Ranieri", participants: 20 },
  { season: "25/26", guanabara: "Felippe Leite", first: "", second: "", third: "", fourth: "", participants: 21 },
  { season: "26/27", guanabara: "", first: "", second: "", third: "", fourth: "", participants: 21 },
  { season: "27/28", guanabara: "", first: "", second: "", third: "", fourth: "", participants: 21 },
  { season: "28/29", guanabara: "", first: "", second: "", third: "", fourth: "", participants: 21 },
];

const predictionMetadataByImage = {
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.46.jpeg": {
    phase: "Oitavas",
    title: "Atlético de Madrid x Tottenham",
    official: "Atlético 5 x 2 Tottenham | Tottenham 3 x 2 Atlético | classificado: Atlético de Madrid",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.48 (1).jpeg": {
    phase: "Oitavas",
    title: "Galatasaray x Liverpool",
    official: "Galatasaray 1 x 0 Liverpool | Liverpool 4 x 0 Galatasaray | classificado: Liverpool",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47.jpeg": {
    phase: "Oitavas",
    title: "Paris Saint-Germain x Chelsea",
    official: "Paris 5 x 2 Chelsea | Chelsea 0 x 3 Paris | classificado: Paris Saint-Germain",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (1).jpeg": {
    phase: "Oitavas",
    title: "Real Madrid x Manchester City",
    official: "Real Madrid 3 x 0 Man City | Man City 1 x 2 Real Madrid | classificado: Real Madrid",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (2).jpeg": {
    phase: "Oitavas",
    title: "Newcastle x Barcelona",
    official: "Newcastle 1 x 1 Barcelona | Barcelona 7 x 2 Newcastle | classificado: Barcelona",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (3).jpeg": {
    phase: "Oitavas",
    title: "Bodø/Glimt x Sporting",
    official: "Bodø/Glimt 3 x 0 Sporting | Sporting 5 x 0 Bodø/Glimt aet | classificado: Sporting CP",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (5).jpeg": {
    phase: "Oitavas",
    title: "Bayer Leverkusen x Arsenal",
    official: "Leverkusen 1 x 1 Arsenal | Arsenal 2 x 0 Leverkusen | classificado: Arsenal",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.48.jpeg": {
    phase: "Oitavas",
    title: "Atalanta x Bayern de Munique",
    official: "Atalanta 1 x 6 Bayern | Bayern 4 x 1 Atalanta | classificado: Bayern München",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (9).jpeg": {
    phase: "Playoff",
    title: "Monaco x Paris Saint-Germain",
    official: "Monaco 2 x 3 Paris | Paris 2 x 2 Monaco | classificado: Paris Saint-Germain",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (10).jpeg": {
    phase: "Playoff",
    title: "Borussia Dortmund x Atalanta",
    official: "Dortmund 2 x 0 Atalanta | Atalanta 4 x 1 Dortmund | classificado: Atalanta",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (11).jpeg": {
    phase: "Playoff",
    title: "Benfica x Real Madrid",
    official: "Benfica 0 x 1 Real Madrid | Real Madrid 2 x 1 Benfica | classificado: Real Madrid",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (12).jpeg": {
    phase: "Playoff",
    title: "Galatasaray x Juventus",
    official: "Galatasaray 5 x 2 Juventus | Juventus 3 x 2 Galatasaray aet | classificado: Galatasaray",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (13).jpeg": {
    phase: "Playoff",
    title: "Qarabağ x Newcastle",
    official: "Qarabağ 1 x 6 Newcastle | Newcastle 3 x 2 Qarabağ | classificado: Newcastle",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (14).jpeg": {
    phase: "Playoff",
    title: "Olympiacos x Bayer Leverkusen",
    official: "Olympiacos 0 x 2 Leverkusen | Leverkusen 0 x 0 Olympiacos | classificado: Bayer Leverkusen",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (15).jpeg": {
    phase: "Playoff",
    title: "Bodø/Glimt x Internazionale",
    official: "Bodø/Glimt 3 x 1 Inter | Inter 1 x 2 Bodø/Glimt | classificado: Bodø/Glimt",
  },
  "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (16).jpeg": {
    phase: "Playoff",
    title: "Club Brugge x Atlético de Madrid",
    official: "Club Brugge 3 x 3 Atlético | Atlético 4 x 1 Club Brugge | classificado: Atlético de Madrid",
  },
};

const predictionImageGroups = [
  {
    phase: "Oitavas",
    folderLabel: "Oitavas - imagens salvas",
    images: [
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.46.jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47.jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (1).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (2).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (3).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (4).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (5).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.47 (6).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.48.jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.22.09/WhatsApp Image 2026-03-10 at 13.40.48 (1).jpeg",
    ],
  },
  {
    phase: "Playoff",
    folderLabel: "Playoff - imagens salvas",
    images: [
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44.jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (1).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (2).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (3).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (4).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (5).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (6).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (7).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (8).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (9).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (10).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (11).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (12).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (13).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (14).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (15).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (16).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (17).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (18).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (19).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (20).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (21).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (22).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (23).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (24).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (25).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (26).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (27).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.23.59/WhatsApp Image 2026-03-20 at 22.23.44 (28).jpeg",
    ],
  },
  {
    phase: "Complementares",
    folderLabel: "Lote complementar - imagens salvas",
    images: [
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.15.jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.15 (1).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.15 (2).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.15 (3).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.15 (4).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16.jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (1).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (2).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (3).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (4).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (5).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (6).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (7).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (8).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (9).jpeg",
      "/Users/leopicca/Downloads/06_Projetos_e_Criacao/WhatsApp Unknown 2026-03-20 at 22.54.23/WhatsApp Image 2026-03-20 at 22.54.16 (10).jpeg",
    ],
  },
];

function buildPredictionEntry(image, phase, folderLabel, index) {
  const metadata = predictionMetadataByImage[image];
  return {
    phase: metadata?.phase || phase,
    title: metadata?.title || `${folderLabel} • imagem ${String(index + 1).padStart(2, "0")}`,
    official: metadata?.official || "Imagem adicionada da pasta salva. Resultado oficial ainda não mapeado nesta tela.",
    status: metadata ? "confirmado" : "imagem",
    image,
  };
}

window.predictionsGallery = predictionImageGroups.flatMap((group) =>
  group.images.map((image, index) => buildPredictionEntry(image, group.phase, group.folderLabel, index))
);
